export const DEPARTMENTS = [
  "Producers",
  "Production",
  "Accounts",
  "Directors",
  "Assistant Directors",
  "Camera",
  "DIT",
  "Sound",
  "Video",
  "Art Department",
  "Construction",
  "Set Decoration",
  "Costume",
  "Costume FX",
  "Hair & Make-up",
  "Prosthetics",
  "Props",
  "Prop Making",
  "SFX",
  "Electrical",
  "Stunts",
  "Locations",
  "Transport",
  "VFX",
] as const;

export type Department = (typeof DEPARTMENTS)[number];

export const DEPARTMENT_ROLES: Record<Department, readonly string[]> = {
  Producers: [
    "Showrunner",
    "Executive Producer",
    "Co-Executive Producer",
    "Co-Producer",
    "Producer",
    "Writer",
    "Story Editor",
  ],
  Production: [
    "Unit Production Manager",
    "Production Manager",
    "Production Coordinator",
    "Production Secretary",
    "Production Assistant",
    "Assets Supervisor",
    "Cast Agreements Coordinator",
  ],
  Accounts: [
    "Financial Controller",
    "Production Accountant",
    "Assistant Accountant",
    "Construction Accountant",
    "Payroll Accountant",
    "Accounts Assistant",
  ],
  Directors: ["Director", "2nd Unit Director"],
  "Assistant Directors": [
    "Assistant Director",
    "Crowd Coordinator",
    "Crowd Fittings Coordinator",
    "Floor PA",
  ],
  Camera: [
    "Director of Photography",
    "Camera Operator",
    "Steadicam Operator",
    "1st AC",
    "2nd AC",
    "Central Loader",
    "Camera Trainee",
  ],
  DIT: ["DIT", "Data Manager", "DIT Trainee"],
  Sound: [
    "Production Sound Mixer",
    "Assistant Sound",
    "Sound Maintenance Engineer",
    "Sound Assistant",
    "Sound Trainee",
  ],
  Video: ["Video Playback Operator", "Video Operator", "Video Assistant", "Video Trainee"],
  "Art Department": [
    "Production Designer",
    "Art Director",
    "Standby Art Director",
    "Assistant Art Director",
    "Design Assistant",
    "Graphic Designer",
    "Graphic Artist",
    "Art Department Coordinator",
    "Art Department Assistant",
    "Art Department Trainee",
  ],
  Construction: [
    "Construction Manager",
    "Construction Foreman",
    "Production Buyer",
    "Construction Administrator",
    "Carpenter",
    "Engineer",
    "Metal Worker",
    "Painter",
    "Plasterer",
    "Plasterers Labourer",
    "Sculptor",
    "Rigger",
    "Stagehand",
  ],
  "Set Decoration": [
    "Set Decorator",
    "Assistant Set Decorator",
    "Production Buyer",
    "Petty Cash Buyer",
    "Set Dec Coordinator",
    "Textiles Buyer",
    "Drapes Master",
    "Drapesperson",
    "Draughtsperson",
    "Set Dec Assistant",
    "Set Dec Trainee",
  ],
  Costume: [
    "Costume Designer",
    "Costume Supervisor",
    "Wardrobe Supervisor",
    "Assistant Costume Designer",
    "Costume Coordinator",
    "Costume Buyer",
    "Set Costumier",
    "Crowd Costumier",
    "Costume Maker",
    "Cutter",
    "Milliner",
    "Embroiderer",
    "Textile Artist",
    "Alterations Assistant",
    "Costume Trainee",
  ],
  "Costume FX": [
    "Armour Supervisor",
    "Armour Sculptor",
    "Fabricator",
    "Modeller",
    "Mouldmaker",
    "Painter",
    "Costume FX Trainee",
  ],
  "Hair & Make-up": [
    "Hair & Make-Up Designer",
    "Hair & Make-Up Supervisor",
    "Hair & Make-Up Artist",
    "Hair & Make-Up Junior",
    "Hair & Make-Up Trainee",
    "Hair & Make-Up Coordinator",
    "Crowd Hair & Make-Up Artist",
  ],
  Prosthetics: [
    "Prosthetics Designer",
    "Prosthetics Supervisor",
    "Prosthetics Makeup Artist",
    "Workshop Manager",
    "Mouldmaker",
    "Sculptor",
    "Modeller",
    "3D Modeller",
    "Fabricator",
    "Wig Maker",
    "Art Finisher",
    "Prosthetics Technician",
    "Prosthetics Trainee",
  ],
  Props: [
    "Prop Master",
    "Assistant Prop Master",
    "Action Prop Supervisor",
    "Standby Props",
    "Dressing Props",
    "Props Storeman",
    "Props Carpenter",
    "Props Painter",
    "Action Prop Buyer",
    "Petty Cash Buyer",
    "Concept Artist",
    "Props Trainee",
  ],
  "Prop Making": [
    "Prop Modeller",
    "Digital Prop Modeller",
    "Workshop Supervisor",
    "Prop Making Buyer",
    "Prop Making Coordinator",
    "Carpenter",
    "Painter",
    "Junior Prop Modeller",
  ],
  SFX: [
    "SFX Supervisor",
    "SFX Coordinator",
    "SFX Technician",
    "SFX Workshop Supervisor",
    "SFX Health & Safety Officer",
    "SFX Motion Control Consultant",
    "SFX Trainee",
  ],
  Electrical: [
    "Gaffer",
    "Best Boy",
    "Rigging Gaffer",
    "Electrician",
    "Rigging Electrician",
    "Electrical Rigger",
    "Desk Operator",
    "Electrical Coordinator",
    "Electrical Trainee",
  ],
  Stunts: [
    "Stunt Coordinator",
    "Assistant Stunt Coordinator",
    "Stunt Rigger",
    "Stunt Performer",
    "Stunt Equipment Wrangler",
  ],
  Locations: [
    "Location Manager",
    "Location Coordinator",
    "Assistant Location Manager",
    "Unit Manager",
    "Location Assistant",
  ],
  Transport: [
    "Transport Manager",
    "Transport Coordinator",
    "Driver",
    "Unit Driver",
    "Runaround Driver",
    "Facilities Driver",
    "Tech Truck Driver",
    "Minibus Driver",
  ],
  VFX: [
    "VFX Supervisor",
    "VFX Producer",
    "VFX Production Manager",
    "VFX Coordinator",
    "VFX Editor",
    "VFX Designer",
    "On Set VFX Supervisor",
    "Data Wrangler",
    "Compositor",
    "VFX Production Assistant",
  ],
};
