export const DEPARTMENTS = [
  "Accounts",
  "Animation",
  "Art Department",
  "Assistant Directors",
  "Camera",
  "Cast",
  "Casting",
  "Color & Finishing",
  "Construction",
  "Costume FX",
  "Costume",
  "Craft Services",
  "Directors",
  "DIT",
  "Editorial",
  "Electrical",
  "Grip",
  "Hair & Make-up",
  "Legal & Business Affairs",
  "Locations",
  "Medical & Safety",
  "Music",
  "Post Sound",
  "Producers",
  "Production",
  "Prop Making",
  "Props",
  "Prosthetics",
  "Publicity & Marketing",
  "Script & Continuity",
  "Set Decoration",
  "SFX",
  "Sound",
  "Studio & Stage",
  "Stunts",
  "Transport",
  "VFX",
  "Video",
  "Writing",
] as const;

export type Department = (typeof DEPARTMENTS)[number];

export const DEPARTMENT_ROLES: Record<Department, readonly string[]> = {
  Producers: [
    "Associate Producer",
    "Co-Executive Producer",
    "Co-Producer",
    "Executive Producer",
    "Line Producer",
    "Producer",
    "Showrunner",
    "Story Editor",
    "Supervising Producer",
    "Writer",
  ],
  Production: [
    "Assets Supervisor",
    "Cast Agreements Coordinator",
    "Office PA",
    "Production Assistant",
    "Production Coordinator",
    "Production Manager",
    "Production Secretary",
    "Production Supervisor",
    "Set PA",
    "Unit Production Manager",
  ],
  Accounts: [
    "Accounts Assistant",
    "Accounts Payable Clerk",
    "Assistant Accountant",
    "Construction Accountant",
    "Financial Controller",
    "Payroll Accountant",
    "Post Accountant",
    "Production Accountant",
  ],
  Writing: [
    "Executive Story Editor",
    "Screenwriter",
    "Script Consultant",
    "Script Coordinator",
    "Staff Writer",
    "Story Consultant",
    "Story Editor",
    "Writers' Assistant",
    "Writers' PA",
  ],
  Casting: [
    "Background Casting",
    "Casting Assistant",
    "Casting Associate",
    "Casting Director",
    "Extras Casting Coordinator",
  ],
  Cast: [
    "Animal Performer",
    "Background",
    "Body Double",
    "Day Player",
    "Guest Star",
    "Photo Double",
    "Principal Cast",
    "Recurring",
    "Stand-in",
    "Stunt Performer",
    "Supporting Cast",
    "Voice Actor",
  ],
  Directors: ["2nd Unit Director", "Director's Assistant", "Director"],
  "Assistant Directors": [
    "Assistant Director",
    "Crowd Coordinator",
    "Crowd Fittings Coordinator",
    "Floor PA",
    "Key Set PA",
  ],
  Camera: [
    "1st AC",
    "2nd AC",
    "Aerial DP",
    "Camera Operator",
    "Camera Trainee",
    "Central Loader",
    "Director of Photography",
    "Drone Operator",
    "Steadicam Operator",
    "Still Photographer",
  ],
  DIT: ["Data Manager", "DIT Trainee", "DIT"],
  Sound: [
    "Assistant Sound",
    "Boom Operator",
    "Production Sound Mixer",
    "RF Tech",
    "Sound Assistant",
    "Sound Maintenance Engineer",
    "Sound Trainee",
    "Sound Utility",
  ],
  Video: ["Video Assistant", "Video Operator", "Video Playback Operator", "Video Trainee"],
  "Art Department": [
    "Art Department Assistant",
    "Art Department Coordinator",
    "Art Department Trainee",
    "Art Director",
    "Assistant Art Director",
    "Design Assistant",
    "Graphic Artist",
    "Graphic Designer",
    "Greens Person",
    "Illustrator",
    "Model Maker",
    "On-Set Dresser",
    "Production Designer",
    "Set Designer",
    "Standby Art Director",
    "Storyboard Artist",
  ],
  Construction: [
    "Carpenter",
    "Construction Administrator",
    "Construction Foreman",
    "Construction Manager",
    "Engineer",
    "Metal Worker",
    "Painter",
    "Plasterer",
    "Plasterers Labourer",
    "Production Buyer",
    "Rigger",
    "Sculptor",
    "Stagehand",
  ],
  "Set Decoration": [
    "Assistant Set Decorator",
    "Drapes Master",
    "Drapesperson",
    "Draughtsperson",
    "Lead Person",
    "Petty Cash Buyer",
    "Production Buyer",
    "Set Dec Assistant",
    "Set Dec Coordinator",
    "Set Dec Trainee",
    "Set Decorator",
    "Swing Gang",
    "Textiles Buyer",
  ],
  Costume: [
    "Ager/Dyer",
    "Alterations Assistant",
    "Assistant Costume Designer",
    "Costume Buyer",
    "Costume Coordinator",
    "Costume Designer",
    "Costume Illustrator",
    "Costume Maker",
    "Costume Supervisor",
    "Costume Trainee",
    "Crowd Costumier",
    "Cutter",
    "Embroiderer",
    "Milliner",
    "Seamstress",
    "Set Costumier",
    "Tailor",
    "Textile Artist",
    "Wardrobe Supervisor",
  ],
  "Costume FX": [
    "Armour Sculptor",
    "Armour Supervisor",
    "Costume FX Trainee",
    "Fabricator",
    "Modeller",
    "Mouldmaker",
    "Painter",
  ],
  "Hair & Make-up": [
    "Body Painter",
    "Crowd Hair & Make-Up Artist",
    "Hair & Make-Up Artist",
    "Hair & Make-Up Coordinator",
    "Hair & Make-Up Designer",
    "Hair & Make-Up Junior",
    "Hair & Make-Up Supervisor",
    "Hair & Make-Up Trainee",
    "Special Effects Makeup Artist",
  ],
  Prosthetics: [
    "3D Modeller",
    "Art Finisher",
    "Fabricator",
    "Modeller",
    "Mouldmaker",
    "Prosthetics Designer",
    "Prosthetics Makeup Artist",
    "Prosthetics Supervisor",
    "Prosthetics Technician",
    "Prosthetics Trainee",
    "Sculptor",
    "Wig Maker",
    "Workshop Manager",
  ],
  "Script & Continuity": ["Script Supervisor"],
  Props: [
    "Action Prop Buyer",
    "Action Prop Supervisor",
    "Assistant Prop Master",
    "Concept Artist",
    "Dressing Props",
    "Petty Cash Buyer",
    "Prop Master",
    "Props Carpenter",
    "Props Painter",
    "Props Storeman",
    "Props Trainee",
    "Standby Props",
  ],
  "Prop Making": [
    "Carpenter",
    "Digital Prop Modeller",
    "Junior Prop Modeller",
    "Painter",
    "Prop Making Buyer",
    "Prop Making Coordinator",
    "Prop Modeller",
    "Workshop Supervisor",
  ],
  SFX: [
    "Armorer",
    "Mechanical Effects Technician",
    "Pyrotechnician",
    "SFX Coordinator",
    "SFX Health & Safety Officer",
    "SFX Motion Control Consultant",
    "SFX Supervisor",
    "SFX Technician",
    "SFX Trainee",
    "SFX Workshop Supervisor",
  ],
  Electrical: [
    "Best Boy",
    "Desk Operator",
    "Dimmer Operator",
    "Electrical Coordinator",
    "Electrical Rigger",
    "Electrical Trainee",
    "Electrician",
    "Gaffer",
    "Generator Operator",
    "Lighting Console Programmer",
    "Rigging Electrician",
    "Rigging Gaffer",
  ],
  Grip: [
    "Best Boy Grip",
    "Crane Operator",
    "Dolly Grip",
    "Grip",
    "Key Grip",
    "Rigging Grip",
    "Rigging Key Grip",
  ],
  Stunts: [
    "Assistant Stunt Coordinator",
    "Fight Choreographer",
    "Precision Driver",
    "Stunt Coordinator",
    "Stunt Equipment Wrangler",
    "Stunt Performer",
    "Stunt Rigger",
  ],
  VFX: [
    "CG/3D Artist",
    "Compositor",
    "Data Wrangler",
    "Matte Painter",
    "Mocap Technician",
    "Motion Capture Supervisor",
    "On Set VFX Supervisor",
    "Previs Supervisor",
    "Roto/Paint Artist",
    "VFX Coordinator",
    "VFX Designer",
    "VFX Editor",
    "VFX Producer",
    "VFX Production Assistant",
    "VFX Production Manager",
    "VFX Supervisor",
  ],
  Editorial: [
    "Additional Editor",
    "ADR Editor",
    "Assistant Editor",
    "Dialogue Editor",
    "Editor",
    "Music Editor",
    "Post Production Coordinator",
    "Post Production Supervisor",
    "VFX Editor",
  ],
  "Post Sound": [
    "ADR Mixer",
    "ADR Recordist",
    "Foley Artist",
    "Foley Editor",
    "Foley Mixer",
    "Re-Recording Mixer",
    "Sound Designer",
    "Sound Effects Editor",
    "Supervising Sound Editor",
  ],
  Music: [
    "Composer",
    "Conductor",
    "Music Contractor",
    "Music Editor",
    "Music Programmer",
    "Music Supervisor",
    "Orchestrator",
    "Session Player",
  ],
  "Color & Finishing": [
    "Assistant Colorist",
    "Colorist",
    "Conform Editor",
    "DI Producer",
    "Mastering Tech",
    "Online Editor",
  ],
  Animation: [
    "Animation Director",
    "Animation Supervisor",
    "Animator",
    "Background Painter",
    "Character Designer",
    "FX Animator",
    "Layout Artist",
    "Lighting TD",
    "Modeler",
    "Render Wrangler",
    "Rigger",
    "Story Editor",
    "Storyboard Artist",
    "Texture Artist",
  ],
  Locations: [
    "Assistant Location Manager",
    "Location Assistant",
    "Location Coordinator",
    "Location Manager",
    "Location PA",
    "Location Scout",
    "Locations Marshal",
    "Unit Manager",
  ],
  Transport: [
    "Driver",
    "Facilities Driver",
    "Minibus Driver",
    "Picture Car Coordinator",
    "Picture Vehicle Driver",
    "Runaround Driver",
    "Tech Truck Driver",
    "Transport Captain",
    "Transport Coordinator",
    "Transport Manager",
    "Unit Driver",
  ],
  "Legal & Business Affairs": [
    "Business Affairs Executive",
    "Clearance Coordinator",
    "Production Counsel",
    "Rights & Clearances",
  ],
  "Craft Services": ["Catering Chef", "Catering Staff", "Craft Service Assistant", "Craft Service"],
  "Studio & Stage": ["Stage Manager", "Studio Manager", "Studio Teacher"],
  "Medical & Safety": ["Health Safety Supervisor", "Intimacy Coordinator", "Set Medic"],
  "Publicity & Marketing": [
    "Distribution Executive",
    "EPK Crew",
    "Marketing Executive",
    "Publicist",
    "Social Media Manager",
    "Unit Publicist",
  ],
};
