export const DEPARTMENTS = [
  "Camera",
  "Sound",
  "Production",
  "Direction",
  "Editorial",
  "Art",
  "Costume",
  "Hair & Makeup",
  "Grip",
  "Electrical",
  "VFX",
  "Post-Production",
  "Stunts",
  "Locations",
  "Catering",
  "Transport",
  "Other",
] as const;

export type Department = (typeof DEPARTMENTS)[number];

export const DEPARTMENT_ROLES: Record<Department, readonly string[]> = {
  Camera: [
    "Director of Photography",
    "Camera Operator",
    "Focus Puller",
    "Clapper Loader",
    "Camera Trainee",
    "Steadicam Operator",
    "Video Split Operator",
    "DIT",
  ],
  Sound: ["Production Sound Mixer", "Boom Operator", "Sound Assistant", "Playback Operator"],
  Production: [
    "Producer",
    "Executive Producer",
    "Line Producer",
    "Production Manager",
    "Production Coordinator",
    "Production Secretary",
    "Production Assistant",
    "Runner",
    "Casting Director",
  ],
  Direction: [
    "Director",
    "First Assistant Director",
    "Second Assistant Director",
    "Third Assistant Director",
    "Floor Runner",
    "Script Supervisor",
  ],
  Editorial: [
    "Editor",
    "Assistant Editor",
    "Post Production Supervisor",
    "Post Production Coordinator",
  ],
  Art: [
    "Production Designer",
    "Art Director",
    "Set Decorator",
    "Prop Master",
    "Props Buyer",
    "Standby Props",
    "Dressing Props",
    "Construction Manager",
    "Scenic Artist",
    "Draughtsperson",
    "Art Department Assistant",
  ],
  Costume: [
    "Costume Designer",
    "Costume Supervisor",
    "Costume Standby",
    "Dresser",
    "Costume Assistant",
    "Crowd Costume Supervisor",
  ],
  "Hair & Makeup": [
    "Hair & Makeup Designer",
    "Hair & Makeup Supervisor",
    "Hair & Makeup Artist",
    "Prosthetics Artist",
    "Crowd Hair & Makeup Supervisor",
    "Hair & Makeup Assistant",
  ],
  Grip: ["Key Grip", "Best Boy Grip", "Grip", "Dolly Grip", "Rigging Grip", "Crane Technician"],
  Electrical: [
    "Gaffer",
    "Best Boy Electric",
    "Electrician",
    "Rigging Gaffer",
    "Rigging Electrician",
    "Generator Operator",
    "Lighting Technician",
  ],
  VFX: [
    "VFX Supervisor",
    "VFX Producer",
    "Special Effects Supervisor",
    "Special Effects Technician",
    "Special Effects Assistant",
    "Pyrotechnician",
  ],
  "Post-Production": ["Colourist", "Sound Designer", "Re-Recording Mixer", "Foley Artist"],
  Stunts: ["Stunt Coordinator", "Stunt Performer", "Stunt Double", "Wire Rigger"],
  Locations: ["Location Manager", "Assistant Location Manager", "Unit Manager"],
  Catering: ["Caterer", "Chef", "Catering Assistant"],
  Transport: [
    "Transport Captain",
    "Transport Coordinator",
    "Unit Driver",
    "Facilities Driver",
    "Camera Car Driver",
    "Minibus Driver",
  ],
  Other: ["Crew Member"],
};
